### ISSUE TITLE
Update license and other github files

### ISSUE THREAD

**Issue by bbrk24** [bbrk24/conniebot#1]
- [ ] The [LICENSE](https://github.com/bbrk24/conniebot/blob/master/LICENSE) currently still has the original text by @xsduan. This should be updated.
- [ ] The [README](https://github.com/bbrk24/conniebot/blob/master/README.md) should be formalized, and a demo of Praat notation should be added.
    *This was already partially updated in commit [`3df5e9f`](https://github.com/bbrk24/conniebot/commit/3df5e9f86279b1775531bae741288fe432bf87b9).*
- [ ] [CONTRIBUTING.md](https://github.com/bbrk24/conniebot/blob/master/CONTRIBUTING.md) should also be updated, as I don't plan to merge `bbrk24:master` back into `xsduan:master`.
- [ ] A SECURITY.md file should be added.

**Comment by xsduan** [comment]
Do you want me to make you a contributor on the main repo instead?

**Comment by bbrk24** [comment]
Whatever works best for you. I've already added myself to [package.json](https://github.com/bbrk24/conniebot/blob/master/package.json#L20); I only just remembered I need to update LICENSE as well.

**Comment by xsduan** [comment]
Yeah, I don't plan on working with it anymore, so go nuts I suppose. I'm gonna keep it under my name just so any links out there still work but you'll be in charge of everything.
